wbinsights/qa/urls.py
from django.urls import path
from . import views
from .views import AnswerEditView, EditQuestionView, QuestionListView

app_name = 'qa'

urlpatterns = [
    path('', QuestionListView.as_view(), name='question_list'),
    path('question/<int:pk>/', views.question_detail, name='question_detail'),
    path('question/new/', views.create_question, name='create_question'),
    path('answer/<int:answer_id>/best/', views.choose_best_answer, name='choose_best_answer'),
    path('question/<int:pk>/edit/', EditQuestionView.as_view(), name='edit_question'),  # Маршрут для редактирования вопроса
    path('answer/<int:pk>/edit/', AnswerEditView.as_view(), name='edit_answer'),  # Маршрут для редактирования ответа

]

wbinsights/wbinsights/urls.py
from django.conf.urls.static import static
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog
from wbinsights import settings

urlpatterns = [
    path('', include('web.urls')),
    path('wbqa/', include('wbqa.urls')),
    path('expert/',include('expertprojects.urls')),
    path('appointment/', include('wbappointment.urls')),
    path(r'jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path(r'comments/', include('django_comments_xtd.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wbinsights/web/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse


"""---  Пользователи ---"""
class CustomUser(AbstractUser):
    email = models.EmailField(_("email address"), unique=True, )

    is_active = models.BooleanField(
        _("active"),
        default=False,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.email


"""--- Статьи ---"""
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=Article.Status.PUBLISHED)


class Image(models.Model):
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    article = models.ForeignKey('Article', related_name='image', on_delete=models.CASCADE)

    def __str__(self):
        return f"Image for {self.article}"


class Article(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубликовано'

    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    # author = models.ForeignKey('User', on_delete=models.SET_NULL)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(choices=Status.choices, default=Status.DRAFT)
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='article', blank=True)

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-time_create']
        indexes = [
            models.Index(fields=['-time_create'])
        ]

    def get_absolute_url(self):
        # return reverse('article_detail', kwargs={'article_slug': self.slug})
        return reverse('article_detail', kwargs={'slug': self.slug})


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})
    

class Research(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)    

wbinsights/web/templates/basePostList.html
{% extends 'base123.html' %}

{% load static %}
{% load web_tags %}
{% load i18n %}



{% block center_col %}

    <link rel="stylesheet" href="{% static 'web/css/basepost_list_css.css' %}?ver=0.01">


    {% include 'components/news_carousel_component.html' %}

    <div class="d-block d-xl-none">
        {% include "components/left_menu/advertisement_left_menu.html" %}
    </div>


    {% include 'components/cbr_rates.html' %}


    {% split request.path "/" 'first' as url_first_part %}

    <div class="d-block d-md-none mb-3">
        <div class="dropdown post-menu">
            <button class="dropbtn" onclick="toggleDropdown(event)">
                {% if url_first_part == 'researches' %}
                    {% trans 'ResearchesLabel' %}
                {% elif url_first_part == 'articles' %}
                    {% trans 'ArticlesLabel' %}
                {% elif url_first_part == 'wbqa' or url_first_part == 'question_answer' %}
                    {% trans 'QuestionAnswerLabel' %}
                {% else %}
                    {% trans 'ExpertsLabel' %}
                {% endif %}
                <span class="arrow-down"></span>
            </button>

            <div class="dropdown-content">
                {% if url_first_part != 'researches' %}
                    <a href="{% url 'research_list' %}" class="text-dark p-3 justify-content-center text-decoration-none d-flex g-fs-14 fw-semibold">{% trans 'ResearchesLabel' %}</a>
                {% endif %}
                {% if url_first_part != 'experts' and url_first_part != '' %}
                    <a href="{% url 'experts_list' %}" class="text-dark p-3 justify-content-center text-decoration-none d-flex g-fs-14 fw-semibold">{% trans 'ExpertsLabel' %}</a>
                {% endif %}
                {% if url_first_part != 'articles' %}
                    <a href="{% url 'article_list' %}" class="text-dark p-3 justify-content-center text-decoration-none d-flex g-fs-14 fw-semibold">{% trans 'ArticlesLabel' %}</a>
                {% endif %}
                {% if url_first_part != 'wbqa' and url_first_part != 'question_answer' %}
                    <a href="{% url 'question_list' %}"
                       class="text-dark p-3 justify-content-center text-decoration-none d-flex g-fs-14 fw-semibold">{% trans 'QuestionAnswerLabel' %}</a>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="d-none d-md-flex justify-content-around mb-3">
        <a href="{% url 'research_list' %}"
   class="p-2 cursor-pointer w-25 d-flex rounded-4 justify-content-center text-decoration-none text-secondary fw-semibold {% if url_first_part == 'researches' %} bg-primary-base-drop text-white {% endif %}">
            {% trans 'ResearchesLabel' %}
        </a>
        <a href="{% url 'experts_list' %}"
   class="p-2 cursor-pointer w-25 d-flex rounded-4 justify-content-center text-decoration-none text-secondary fw-semibold {% if url_first_part == 'experts' or url_first_part == '' %} bg-primary-base-drop text-white {% endif %}">
            {% trans 'ExpertsLabel' %}
        </a>
        <a href="{% url 'article_list' %}"
           class="p-2 cursor-pointer w-25 d-flex rounded-4 justify-content-center text-decoration-none text-secondary fw-semibold {% if url_first_part == 'articles' %} bg-primary-base-drop text-white {% endif %}">
            {% trans 'ArticlesLabel' %}
        </a>
        <a href="{% url 'question_list' %}"
           class="p-2 cursor-pointer w-25 d-flex rounded-4 justify-content-center text-decoration-none text-secondary fw-semibold {% if url_first_part == 'wbqa' or url_first_part == 'question_answer' %} bg-primary-base-drop text-white {% endif %}">
            {% trans 'QuestionAnswerLabel' %}
        </a>
    </div>

    <div id="article_list" class="content-block">
        {% block posts_content %}{% endblock %}
    </div>


    <script>

        function toggleDropdown(event) {
            event.stopPropagation();
            var dropdown = event.currentTarget.nextElementSibling;
            if (dropdown.style.display === "block") {
                dropdown.style.display = "none";
            } else {
                dropdown.style.display = "block";
            }
        }

        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                for (var i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.style.display === "block") {
                        openDropdown.style.display = "none";
                    }
                }
            }
        }

    </script>


{% endblock %}

wbinsights/web/templates/create_article.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ article_form.as_p }}
    <h2>Images</h2>
    {{ image_formset.management_form }}
    {% for form in image_formset %}
    <div>
        {{ form.as_p }}
    </div>
    {% endfor %}
    <input type="submit" value="Create Article">
</form>

wbinsights/web/templates/expertProfile.html
{% extends 'base.html' %}


{% block content %}
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/expertProfilePage.css') }}">
</head>

<div class="prof-page-cont">
    <a href="{{ url_for('index') }}" class="to-main-page"> <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16" style="font-weight: bold; color:#777786;">
        <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
      </svg> &nbsp;На главную</a>

    <div class="profile-info-cont">

        <div class="top-half">
            <div class="prof-pic-cont">
                <img src="{{ url_for('userava') }}" style="border-radius: 50%; width:150px ; height: 150px">
            </div>
            <div class="profile-information-cont">
                <div class="user-display-name">{{current_user.firstName}}</div>
                <div class="user-rating-cont">
                    <div class="user-rating">Rating: &nbsp;</div>
                    <div class="user-rate-and-stars">4.5 *****</div>
                </div>
                <div class="user-category-cont">
                    <div class="user-category">Эксперт в области:</div>
                    <div class="user-catagory-highlight">IT</div>
                </div>
                <div class="user-stats">10 статей • 30 исследований  • 24 отзыва</div>
                <div class="user-settings">

                    <a class="profile-settings-btn">Настройки профиля</a>
                    <a class="profile-logout-btn" >Выйти</a>

                </div>
                
            </div>

        </div>

        <div class="bottom-half">
            <div class="bottom-info">
                <div class="prof-bottom-cont">
                    <span class="bottom-bold-text">Образование: &nbsp;</span>
                    <span class="">Экономический факультет МГУ имени М.В.Ломоносова</span>
                </div>
                <div class="prof-bottom-cont">
                    <span class="bottom-bold-text">Возраст:&nbsp;</span>
                    <span class="">33 года</span>
                </div>
                <div class="prof-about-me-cont">
                    Сложно сказать, почему активно развивающиеся страны третьего мира представляют собой не что
                    иное, как квинтэссенцию победы маркетинга над разумом и должны быть объявлены
                    нарушающими общечеловеческие нормы этики и морали!
                </div>
                <div class="prof-bottom-cont">
                    <span class="bottom-bold-text">Стоимость консультации:&nbsp;</span>
                    <span class="">1000₽/час</span>
                </div>

            </div>
            <div class="profile-links">
                <div class="each-link-cont">
                    <div class="link-name">Исследования &nbsp;</div>
                    <div class="link-count">30</div>
                </div>
                <div class="each-link-cont">
                    <div class="link-name">Статьи &nbsp;</div>
                    <div class="link-count">10</div>
                </div>
                <div class="each-link-cont">
                    <div class="link-name">Вопросы &nbsp;</div>
                    <div class="link-count">12</div>
                </div>
                <div class="each-link-cont">
                    <div class="link-name">Консультации &nbsp;</div>
                    <div class="link-count"></div>
                </div>
                <div class="each-link-cont">
                    <div class="link-name">Отзывы &nbsp;</div>
                    <div class="link-count"></div>
                </div>
                <div class="each-link-cont">
                    <div class="link-name">Уведомления &nbsp;</div>
                    <div class="link-count"></div>
                </div>

            </div>

        </div>

    </div>
</div>
{% endblock %}

wbinsights/web/templates/index.html
{% extends 'base123.html' %}


{% block center_col %}

   <h1>Test deploy123</h1>
{% endblock %}